// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maqukutdqcqwmvomgrxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hcXVrdXRkcWNxd212b21ncnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODc0NDUsImV4cCI6MjA1OTY2MzQ0NX0.cXmhOUy1-IlG7bXb3WyYp_nRfRkdWByo4T53vmOGBTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);